provider: gemini
model: gemini-2.5-pro
api_key: AIzaSyBdntzaN_WbXPNXyq0p2-vf40ncPix4A0U
max_tokens: 2048        # Reduced from 4096
temperature: 0.05       # Reduced from 0.1
timeout: 120s           # Increased from 60s
max_retries: 5     

rate_limit:
  requests_per_minute: 10
  burst: 2
  wait_time: 5s